"""unique_email

Revision ID: 067c7ff2f20a
Revises: 1afd1b29be86
Create Date: 2024-10-21 23:25:26.538284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067c7ff2f20a'
down_revision: Union[str, None] = '1afd1b29be86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'UserProfile', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserProfile', type_='unique')
    # ### end Alembic commands ###
