"""sendler

Revision ID: befbc252e508
Revises: e027026022a5
Create Date: 2024-10-24 22:40:42.719039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befbc252e508'
down_revision: Union[str, None] = 'e027026022a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('Messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Messages', 'sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Messages', 'created_at')
    # ### end Alembic commands ###
